### ISSUE TITLE
Cannot run npm run build/dev

### ISSUE THREAD

**Issue by faulteh** [lukebarnard1/j#29]
Hi Luke,

I really like your blog in matrix idea and wanted to start on my own instance to tinker with but I'm having problems with the installation. I'm running on Debian Jessie with Node 6.9.4 and NPM  3.10.10

Running npm run build or npm run dev comes up with an error:

I have run npm install and there is a node_modules/matrix-js-sdk directory but only a src dir in there no lib dir. I feel I'm missing something obvious but I'm better with Python than Node.

Regards,
Scott (@faulteh:scriptforge.org)

Error below:

```
matrix@storm:~/j$ npm run build

> j@0.0.1 build /home/matrix/j
> browserify src/index.js -o web/bundle.js -t [ riotify ] -v

Error: Cannot find module './lib/matrix' from '/home/matrix/j/node_modules/matrix-js-sdk'
    at /home/matrix/j/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/matrix/j/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/matrix/j/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/matrix/j/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! j@0.0.1 build: `browserify src/index.js -o web/bundle.js -t [ riotify ] -v`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the j@0.0.1 build script 'browserify src/index.js -o web/bundle.js -t [ riotify ] -v'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the j package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     browserify src/index.js -o web/bundle.js -t [ riotify ] -v
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs j
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls j
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/matrix/j/npm-debug.log

```

**Comment by faulteh** [comment]
Also downgraded my nodejs to 6.2.2 but still had same error.

**Comment by lukebarnard1** [comment]
@faulteh matrix-js-sdk needs to be built before hand. This is quite a recent change to the js sdk so the README.md should be updated. 

I would `cd node_modules/matrix-js-sdk; npm run build` and then build j.

**Comment by lukebarnard1** [comment]
https://github.com/lukebarnard1/j/commit/39dc89d19dff9c0878facd53880ea461499da2d4 alters the README.md to include the matrix-js-sdk build step.
